# Generated by Django 2.2 on 2021-05-16 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='email_address',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
