# Generated by Django 2.2 on 2021-05-16 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0002_users_email_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email_address',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
