# Generated by Django 2.2 on 2021-05-18 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0004_auto_20210516_0230'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
